name: Deploy to Surge

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: echo "Deploying!"
    
    - name: Install Surge
      run: npm install --global surge
    
    - name: Deploy to Surge
      run: surge ./ --domain 20220018.surge.sh --token 477473f5f3e5f454d5842e13a5221663
    
    - name: Visit the website
      run: curl https://20220018.surge.sh